# Generated by Django 4.2.9 on 2024-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('body', models.TextField()),
                ('location', models.CharField(choices=[('WH', 'West Haven'), ('ST', 'Surrounding town')], max_length=2)),
            ],
        ),
    ]
