# Generated by Django 4.2.9 on 2024-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_contact_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(choices=[('WH', 'West Haven'), ('MF', 'Milford'), ('OR', 'Orange'), ('HD', 'Hamden'), ('NH', 'New Haven'), ('NA', 'Other')], max_length=2),
        ),
    ]
