# Generated by Django 4.2.9 on 2024-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='availability',
            field=models.CharField(default='In-Person/Hybrid', max_length=50),
            preserve_default=False,
        ),
    ]
